### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [venomfly1041/GameBase#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by venomfly1041** [comment]
First of all,thank you for your comment!

>>What about using libyui?

I'm willing to use it.However,at least for now,I'm going to stick with ncurses.

The only purpose of this project is to make TUI based games, because I wanted to play games when I Iog into a remote shell.So I don't actually need GUI support immediately.  Besides,as my personal taste, I want to know how to manage ncurses.

If I could manage this project well,and made some good looking progress,then I will consider more about it.
